language: node_js
node_js:
- 18
before_script:
- npm install -g stryker-cli
after_script:
- stryker run
env:
  global:
    secure: i1dTPCaDiefFfLgO+ofK1iUDgtReuB5X1OJKP2wd2YVhdcsbNs4Ta/7wmr2Lf7T1Y4tnrrsehGGCawQoQNzocTfgImq7SQGejmtPQGSH/jOJNT6Ga33chgoemTVv1Qd+DlVsCzzKp8oH5o3TDD6F+mPFq50WYjaln97L8ckoxhDY0nKpOrt9UFLkcND5HW1Q/Iq/tZ6gRitG6MfK2/qf7aOyrUNoKL7/6aWXdFQmHqkkYj2s9RG+jDlyRQr05OPJDOzA2nYRJf832A2kfHettsUmdUQJPIf9NnrdFYam2kLpXhK/2P+ACaRa3yJi9PieEb2epAaPG3fi8y+5ucICWO1v1LAW3/8o5xVGVKPi20cStwN9thUtRyN+pklVXy3g+8mnANbnwsWMrI9z8UnV80iKvn9osNAqZZYVGN2aiQl8qZPu2C1FabHtU7FvvT0eERJmz+Ft06ZTTwcCAqu8jo81uQ7rQT5n+j2/u4wD0YEyvRXjnfjNZlF9ojNG9TkfrVOV57kmgghduTj4b52dvqAw7+P8K1+bx3OCxDcqqT6JxWxZS0Fsu91WaqTRRmXJS08ox4H2V6LHiRJV1sfM90zhvwsz9U8pgQKgCbjxbmagnPgKKgZX0T0nw6L0NYnKW/ExLAudoqC45lNnTjT1SfaJh/wFCd5kdyI9wMHd8/s=
